### ISSUE TITLE
Gitlab: Build notifications not working

### ISSUE THREAD

**Issue by 4ndv** [Requilence/integram#6]
Looks like gitlab's build notifications is not working. Push notifications is working fine, but i'm not receiving anything about build status.

**Comment by Requilence** [comment]
Build notifications are not implemented yet because of lack of the docs [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md)
I need some sample builds payloads to check the structure. If you want to speed up this process feel free to contact me on Telegram – https://telegram.me/requilence

**Comment by 4ndv** [comment]
Everything is awesome now, thanks for this feature!

**Comment by Requilence** [comment]
@4ndv thanks for the help 😉

**Comment by vpetrenko** [comment]
Thank you for the feature, guys! Thought about it yesterday. Today it's already working. Amazing!
